### ISSUE TITLE
Kotlin Runtime Version

### ISSUE THREAD

**Issue by GabrielMorenoIbarra** [skydoves/GithubFollows#14]
I am very grateful for your awesome project template. It is very useful. 

This issue is only a warning that I have tried to solve too many times and perhaps it does not depend on this project, but sincerelly I am so lost now... :-(

`Your version of Kotlin runtime in 'kotlin-stdlib-1.1.51' library is 1.1.51, while plugin version is 1.2.41-release-Studio3.1-1.
`
Moreover, I do not find `1.1.51` in any place on the project.

Any idea?

**Comment by skydoves** [comment]
Hi!

Runtime library should be updated to avoid compatibility problems.
or downgrade project's kotlin version at [here](https://github.com/skydoves/GithubFollows/blob/master/buildSrc/src/main/java/Versions.kt) kotlin value "1.2.21" to " 1.1.51".
if not work about kotlin update or downgrade, [here](http://androidpala.com/outdated-kotlin-runtime/) is an another solution.

Thank you!

**Comment by GabrielMorenoIbarra** [comment]
Thank you so much for the answer!
I had tried your solutions without good results. I guess I have another problem I am not seeing... Anyway, I will continue trying other things. :-)

**Comment by ninad458** [comment]
@GabrielMorenoIbarra could you please check for kotlin runtime update?
It should be Tools>Kotlin>Configure Kotlin Plugin Update>Check for updates

**Comment by GabrielMorenoIbarra** [comment]
It is correct... I have no idea what it is happen... :-(
