### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by kjain9878** [skydoves/GithubFollows#5]
https://github.com/skydoves/GithubFollows/blob/966f1a36ca70b3bbdc4a49916ba49a66bb3f50d1/app/src/main/java/com/skydoves/githubfollows/ApplicationClazz.kt#L24

Here you are calling
```
DaggerAppComponent.builder()
                .application(this)
                .build()
                .inject(this)
```  
and then you are returning 
```
override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.builder().application(this).build()
    }
```
can't you just make a var for `DaggerAppComponent.builder().application(this).build()` and then just call inject on that above.

**Comment by skydoves** [comment]
Oh you mean like this?
```java
class ApplicationClazz : DaggerApplication() {

    val appComponent = DaggerAppComponent.builder()
            .application(this)
            .build()

    override fun onCreate() {
        super.onCreate()

        if (!LeakCanary.isInAnalyzerProcess(this)) {
            LeakCanary.install(this)
        }

        appComponent.inject(this)

        if(BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
        }

        PreferenceComponent_PrefAppComponent.init(this)
    }

    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return appComponent
    }
}
```
I think it's better than before too.
Thanks!!

If you want to contribute any codes or change something,
welcome to Pull Request! :)

**Comment by kjain9878** [comment]
Let's discuss the approach that you have followed. I think we can make the code more robust and better. Add me on FB @kjain9878

**Comment by kjain9878** [comment]
Refactored with PR

**Comment by skydoves** [comment]
okay, Thank you!!
